# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTalk13122018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'

  target 'iOSTalk13122018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
